server:
  port: 8081
spring:
  application:
    name: back-front
  profiles:
    active:
      - '@environment@'
  devtools:
    add-properties: false
mybatis:
  type-aliases-package: cn.gorillahug.front.model
  mapper-locations: classpath:mapper/*.xml
